# Generated by Django 3.0.1 on 2020-02-09 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='img',
            field=models.ImageField(default='r', upload_to='shop/'),
        ),
    ]
