# Generated by Django 3.0.1 on 2020-02-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(default='', max_length=100)),
                ('DateOfBirth', models.DateField()),
            ],
        ),
    ]
